version: '3.8'
services:
  app:
    build:
      context: .
    ports:
      - "8080:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development
      - DB_HOST=postgres
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=node_db
    command: npm run dev
    depends_on:
      - postgres

  postgres:
    image: postgres:15-alpine
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: node_db
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  flyway:
    image: flyway/flyway:latest
    container_name: flyway_container
    depends_on:
      - postgres
    command: -url=jdbc:postgresql://postgres:5432/node_db -user=postgres -password=postgres -locations=filesystem:/flyway/sql migrate
    volumes:
      - ./migrations:/flyway/sql

volumes:
  pg_data: